### ISSUE TITLE
RuntimeException for a undefined StraightLine

### ISSUE THREAD

**Issue by ChristianLutz** [dlegland/javaGeom#6]
Hello,

we found something but we are not sure if this is intended or a bug. We think it shouldn't be possible to create a StraightLine with two (nearly) identical points, because it leads to a RuntimeException.

```
@Test
public void javaGeomCircleStraightLine2DIntersection2() {
    // if center and point are equals, intersections method throw an exception
    Point2D center = new Point2D(174980.60, 66497.20);
    Point2D point = new Point2D(174980.60, 66497.20);
    StraightLine2D straightLine2D = new StraightLine2D(center, point);
    Circle2D circle = new Circle2D(center, 274.10);
    Collection<Point2D> circleIntersections = circle.intersections(straightLine2D);
    Assert.assertTrue(circleIntersections.isEmpty());
 }
```

```
@Test
public void javaGeomCircleStraightLine2DIntersection2() {
    // if center and point are equals, intersections method throw an exception
    Point2D center = new Point2D(174980.6000001, 66497.20);
    Point2D point = new Point2D(174980.60, 66497.20);
    StraightLine2D straightLine2D = new StraightLine2D(center, point);
    Circle2D circle = new Circle2D(center, 274.10);
    Collection<Point2D> circleIntersections = circle.intersections(straightLine2D);
    Assert.assertTrue(circleIntersections.isEmpty());
 }
```

**Comment by dlegland** [comment]
Hello,

you're right, creating such lines should not be allowed.
I have commited a modif that throws an exception when creating a line (or linear shape) with direction vector nearly equal to (0,0).
However, when computing line-circle intersections, your second test case will fail anyway. This can happen because tolerance used for detecting null-direction is larger than some intermediate results in intersection computation.

 I do not have special solution for this. The best I see is to surround by a try-catch block. Otherwise, a possibility is to manually ensure that all lines have direction vector with unit norm.

```
Vector2D direction = new Vector2D(center, point).normalize();
StraightLine2D line = new StraightLine2D(center, direction);
```

hope this helps.

**Comment by ChristianLutz** [comment]
Thank you. Currently we are using the try-catch approach, will check if we can apply the direction vector.
