### ISSUE TITLE
Function contains in class math.geom2d.polygon.SimplePolygon2D.

### ISSUE THREAD

**Issue by smallwood-d** [dlegland/javaGeom#9]
Hello,
I would appreciate your help understanding the _contains_ function in _simplePolygon2D_.
The return statement check if the area is larger than zero (according to your explanation checking if the polygon is clockwise or counter-clockwise) and then re-check with the winding number of the polygon.
_return area > 0.0D?winding == 1:winding==0;_
1. If the winding number of a simple polygon is zero does it mean the point don’t contained in the polygon?
2. I get unexpected result with this input :
* Polygon:
   * (34.85738, 32.283905)
   * (34.85825, 32.294194999999995)
   * (34.88468, 32.29320499999999)
   * (34.88303, 32.283125)
   * (34.85738, 32.283905)
* Point :
   * (34.870909999999995, 32.289199999999994)
* Area : 
   * -2.6633249990482E-4
* Winding numer : 
   * -1

Thank you very much.

**Comment by dlegland** [comment]
Hi,
the result of the function depends on the orientation of the polygon. Most polygons are assumed to be CCW (Counter-ClockWise) oriented. For points located inside a CCW-oriented polygon, the winding number is 1. The winding number of points outside a CCW polygon is 0.

For polygon oriented Clock-wise, I have chosen to consider that a point is *inside* the polygon if it is *outside* the reversed version of the polygon (and vice-versa). So we can keep consistent relationship between (1) the signed area of the polygon, and (2) the winding number and "insideness" of the point.

does this clarify? Otherwise can you provide an example?

**Comment by smallwood-d** [comment]
I didn't understand the second paragraph.

Example : 
* Polygon: (34.85738, 32.283905)
  * (34.85825, 32.294194999999995)
  * (34.88468, 32.29320499999999)
  * (34.88303, 32.283125)
  * (34.85738, 32.283905)

* Point : (34.870909999999995, 32.289199999999994)

* Area : -2.6633249990482E-4

* Winding numer : -1

**Comment by dlegland** [comment]
Your polygon is oriented Clock-Wise. You are in the second case I have described. In that case, the javageom library considers that the point is outside the polygon. You can imagine that the domain enclosed by the polygon is the whole 2D plane, except the domain defined by the polygon boundary.

If you want the result of this specific point/polygon test to be positive, you must ensure that the polygon is CCW oriented. You can simply use the `polygon.complement()` method. The resulting polygon will have same vertices, but in reverse order.

**Comment by smallwood-d** [comment]
Thanks
